[tool.black]
line-length = 99

[tool.mypy]
python_version = 3.11
check_untyped_defs = true
ignore_missing_imports = true
ignore_missing_imports_per_module = true
warn_unused_ignores = true
exclude = ["venv/*"]


[tool.pytest.ini_options]
addopts = "-v --disable-warnings"
markers = [
  "asyncio",
]
minversion = "7.3"
python_files = ["test_*.py", "*_test.py"]
testpaths = ["tests"]